# If you are building a simple GitHub user page (https://username.github.io) then use these settings:
url: "https://ignacio-arce.github.io"
baseurl: "/"


# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: iaSoftware

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Contact: "contact.html"
  Aboutus: "about.html"

# Short description of your site
description: TODO

auto: true
markdown: kramdown
permalink: /:year/:month/:title
rdiscount extensions: [smart]
