url: "https://ignacio-arce.github.io"
baseurl: "/"

title: iaSoftware
subtitle: Making IT solutions for the daily business
author:
  name: Ignacio Arce
  copyright-year: 2020
  email: iarce@dc.uba.ar

whatsapp:
  link: "https://web.whatsapp.com/send?phone=5491167586967&text&source&data&app_absent"
  number: "+54 91167586967"

api:
  url: "https://ignacio-arce.herokuapp.com"

auto: true
permalink: /:year/:month/:title
