url: "https://ignacio-arce.github.io"
baseurl: "/"

title: ignacio arce
author:
  name: Ignacio Arce
  copyright-year: 2020
  email: iarce@dc.uba.ar

whatsapp:
  link: "https://web.whatsapp.com/send?phone=5491167586967&text&source&data&app_absent"
  number: "+54 91167586967"

api:
  url: "https://ignacio-arce.herokuapp.com"

auto: true
permalink: /:year/:month/:title

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "es"]
exclude_from_localizations: ["assets", "img"]
defaultLang: en
default_locale_in_subfolder: true
